name: Clang CI

on: [push, pull_request]

jobs:
  build:
    name: Build project with Clang
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
    - name: Fetching sources
      uses: actions/checkout@v2
    - name: Installing compiler
      run: |
        sudo apt-get update
        sudo apt-get -y install clang
    - name: Installing build system
      run: |
        sudo apt-get -y install cmake make
    - name: Installing development packages
      run: |
        sudo apt-get -y install qtbase5-dev qttools5-dev qttools5-dev-tools
    - name: Preparing for the build
      run: |
        mkdir build
    - name: Building with CMake
      run: |
        pushd build
        cmake -DBUILD_APPLET:BOOL=ON -DBUILD_GUI:BOOL=ON ..
        cmake --build .
        popd
    - name: Installing project
      run: |
        pushd build
        sudo make install
        popd
