#
# SPDX-FileCopyrightText: 2021-2023 EasyCoding Team and contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Flatpak CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

env:
  FLATPAK_ID: org.easycoding.TunedSwitcher
  FLATPAK_BRANCH: test

jobs:
  build:
    name: Build Flatpak bundle
    runs-on: ubuntu-latest
    container:
      image: freedesktopsdk/flatpak:21.08-x86_64
      options: --privileged --tmpfs /tmp -v /var/tmp -v /root/.local/share/flatpak

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Build flatpak
        uses: gasinvein/action-flatpak-build@master
        id: build_flatpak
        with:
          kind: app
          id: ${{ env.FLATPAK_ID }}
          arch: x86_64
          branch: ${{ env.FLATPAK_BRANCH }}
          manifest-path: .github/workflows/flatpak/${{ env.FLATPAK_ID }}.yml
          extra-args: --ccache

      - name: Create bundle
        run: |
          flatpak build-bundle \
            ${{ steps.build_flatpak.outputs.build-repo }} \
            ${FLATPAK_ID}-${{ github.sha }}.flatpak \
            ${FLATPAK_ID} ${FLATPAK_BRANCH}

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FLATPAK_ID }}-${{ github.sha }}
          path: ${{ env.FLATPAK_ID }}-${{ github.sha }}.flatpak
